"""Discrete Environment — generative process for Active Inference simulations.

The environment is the generative PROCESS (ground truth) as opposed to the
agent's generative MODEL.  See glossary.md: "Generative Process".

Notation (from resources/notation_table.md):
    η  — External/environmental hidden states
    o  — Observations generated by the environment
    a  — Actions received from the agent

Cross-course connections (see resources/cross_course_map.md):
    Philosophy M1  — Boundaries, Markov Blankets
    CogSci M1      — Neural assemblies, brain-body-environment
    Math M1        — State spaces, Langevin dynamics
    CS M1          — Generative process vs generative model
"""

import numpy as np
import logging

logger = logging.getLogger(__name__)


class DiscreteEnvironment:
    """Discrete environment (generative process) for Active Inference.

    The environment maintains a true hidden state η, generates
    observations through a true likelihood A, and transitions through
    a true transition model B.  Distinguished from the agent's
    *generative model* which may be an imperfect approximation.

    Parameters
    ----------
    true_A : np.ndarray
        True likelihood P(o|s), shape ``(num_obs, num_states)``.
    true_B : np.ndarray
        True transitions P(s'|s, a), shape ``(num_states, num_states, num_actions)``.
    initial_state : int
        Starting state index.

    Raises
    ------
    ValueError
        If matrices are malformed or *initial_state* is out of range.
    """

    def __init__(
        self,
        true_A: np.ndarray,
        true_B: np.ndarray,
        initial_state: int = 0,
    ):
        self.true_A = np.asarray(true_A, dtype=np.float64)
        self.true_B = np.asarray(true_B, dtype=np.float64)

        # Pre-validate ndim before extracting shape indices
        if self.true_A.ndim != 2:
            raise ValueError(f"true_A must be 2-D, got {self.true_A.ndim}-D")

        self.num_obs: int = self.true_A.shape[0]
        self.num_states: int = self.true_A.shape[1]
        self.num_actions: int = (
            self.true_B.shape[2] if self.true_B.ndim == 3 else 1
        )

        self._validate()

        if not 0 <= initial_state < self.num_states:
            raise ValueError(
                f"initial_state {initial_state} out of range "
                f"[0, {self.num_states})"
            )

        self.state: int = initial_state
        self.timestep: int = 0
        self.history: dict = {
            "states": [initial_state],
            "observations": [],
            "actions": [],
        }

        logger.info(
            "Environment: %d states, %d obs, %d actions, s₀=%d",
            self.num_states, self.num_obs, self.num_actions, initial_state,
        )

    # ------------------------------------------------------------------
    # Validation
    # ------------------------------------------------------------------

    def _validate(self) -> None:
        """Validate A and B dimensions and normalisation.

        Raises
        ------
        ValueError
            On any constraint violation.
        """
        for s in range(self.num_states):
            col_sum = self.true_A[:, s].sum()
            if not np.isclose(col_sum, 1.0):
                raise ValueError(
                    f"true_A column {s} sums to {col_sum:.6f}, expected 1.0"
                )

        if self.true_B.ndim == 3:
            for a in range(self.num_actions):
                for s in range(self.num_states):
                    col_sum = self.true_B[:, s, a].sum()
                    if not np.isclose(col_sum, 1.0):
                        raise ValueError(
                            f"true_B column s={s}, a={a} sums to {col_sum:.6f}"
                        )

    # ------------------------------------------------------------------
    # Dynamics
    # ------------------------------------------------------------------

    def reset(self, initial_state: int = 0) -> int:
        """Reset environment and return initial observation.

        Parameters
        ----------
        initial_state : int
            Starting state index.

        Returns
        -------
        int
            Initial observation sampled from P(o|s₀).

        Raises
        ------
        ValueError
            If *initial_state* is out of range.
        """
        if not 0 <= initial_state < self.num_states:
            raise ValueError(
                f"initial_state {initial_state} out of range "
                f"[0, {self.num_states})"
            )
        self.state = initial_state
        self.timestep = 0
        self.history = {
            "states": [initial_state],
            "observations": [],
            "actions": [],
        }
        obs = self._generate_observation()
        logger.info("Environment reset: state=%d, obs=%d", self.state, obs)
        return obs

    def step(self, action: int) -> int:
        """Execute action and return resulting observation.

        1. Transition: s' ~ P(s'|s, a) = B[:, s, a]
        2. Observe:    o  ~ P(o|s')     = A[:, s']

        Parameters
        ----------
        action : int
            Action index.

        Returns
        -------
        int
            New observation.

        Raises
        ------
        ValueError
            If *action* is out of range.
        """
        if not 0 <= action < self.num_actions:
            raise ValueError(
                f"Action {action} out of range [0, {self.num_actions})"
            )

        # Transition
        if self.true_B.ndim == 3:
            transition_probs = self.true_B[:, self.state, action]
        else:
            transition_probs = self.true_B[:, self.state]

        self.state = int(np.random.choice(self.num_states, p=transition_probs))

        # Observe
        obs = self._generate_observation()

        # Record
        self.timestep += 1
        self.history["actions"].append(action)
        self.history["states"].append(self.state)
        self.history["observations"].append(obs)

        logger.debug(
            "t=%d: action=%d → state=%d, obs=%d",
            self.timestep, action, self.state, obs,
        )
        return obs

    # ------------------------------------------------------------------
    # Queries
    # ------------------------------------------------------------------

    def get_info(self) -> dict:
        """Return current environment metadata.

        Returns
        -------
        dict
            Keys: ``state``, ``timestep``, ``num_states``, ``num_obs``,
            ``num_actions``.
        """
        return {
            "state": self.state,
            "timestep": self.timestep,
            "num_states": self.num_states,
            "num_obs": self.num_obs,
            "num_actions": self.num_actions,
        }

    def _generate_observation(self) -> int:
        """Sample observation from current state: o ~ P(o|s)."""
        obs_probs = self.true_A[:, self.state]
        return int(np.random.choice(self.num_obs, p=obs_probs))

    def __repr__(self) -> str:
        return (
            f"DiscreteEnvironment(states={self.num_states}, "
            f"obs={self.num_obs}, actions={self.num_actions}, "
            f"state={self.state})"
        )
